In [1]:
import numpy as np

In [34]:
x_shape = tuple(map(int, input().split()))
X = np.fromiter(map(int, input().split()), np.int).reshape(x_shape)
y_shape = tuple(map(int, input().split()))
Y = np.fromiter(map(int, input().split()), np.int).reshape(y_shape)

# here goes your solution; X and Y are already defined!
if x_shape[1] != y_shape[1]:
    print("matrix shapes do not match")
else:
    print(np.dot(X,Y.T))

2 3
8 7 7 14 4 6
4 3
5 5 1 5 2 6 3 3 9 1 4 6
[[ 82  96 108  78]
 [ 96 114 108  66]]


In [37]:
mat=2*np.eye(3,4)+np.eye(3,4,1)
mat

array([[ 2.,  1.,  0.,  0.],
       [ 0.,  2.,  1.,  0.],
       [ 0.,  0.,  2.,  1.]])

In [38]:
mat.mean(axis=0)

array([ 0.66666667,  1.        ,  1.        ,  0.33333333])

In [26]:
np.full((2,3),4.).flatten()

array([ 4.,  4.,  4.,  4.,  4.,  4.])

>>> sbux = np.loadtxt("sbux.csv", usecols=(0,1,4), skiprows=1, delimiter=",", 
                      dtype={'names': ('date', 'open', 'close'),
                             'formats': ('datetime64[D]', 'f4', 'f4')})
>>> print(sbux[0:4])
[(datetime.date(2015, 9, 1), 53.0, 57.2599983215332)
 (datetime.date(2015, 8, 3), 58.619998931884766, 54.709999084472656)
 (datetime.date(2015, 7, 1), 53.86000061035156, 57.93000030517578)
 (datetime.date(2015, 6, 1), 51.959999084472656, 53.619998931884766)]

In [40]:
?np.loadtxt

In [47]:
a = [2,4,2,6,6,4]
sum([i**2 for i in a])

112

In [55]:
((np.array([2,4,2,6,6,4])/4)**2).sum()

7.0

In [93]:
from urllib.request import urlopen
filename = 'https://stepic.org/media/attachments/lesson/16462/boston_houses.csv'
f = urlopen(filename)
d = np.loadtxt(f, skiprows=1, delimiter=",")
print(d.mean(axis=0))
y = np.dot(np.linalg.pinv(np.c_[np.ones(d.shape[0]),d[:,1:]]), d[:,0])
print(' '.join(map(str,y)))

[ 22.53280632   3.61352356  11.36363636   0.06916996   0.55469506
   6.28463439   3.79504269]
-3.65580428506 -0.216395502369 0.0737305981755 4.41245057691 -25.4684487841 7.14320155075 -1.30108767765


In [63]:
np.c_[np.ones(4),np.array([[12, 3, 4, 5]]).T]

array([[  1.,  12.],
       [  1.,   3.],
       [  1.,   4.],
       [  1.,   5.]])

In [66]:
np.dot(np.linalg.pinv(np.c_[np.ones(3),np.array([[60,50,75]]).T]), np.array([[10,7,12]]).T)

array([[-2.34210526],
       [ 0.19473684]])